const actionTypes = {
  AUTH_PENDING: 'AUTH_PENDING',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILED: 'AUTH_FAILED',
  FETCH_ACCOUNT_PENDING: 'FETCH_ACCOUNT_PENDING',
  FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
  ACCOUNT_FAILED: 'ACCOUNT_FAILED',
  FETCH_TRANSACTION_SUCCESS: 'FETCH_TRANSACTION_SUCCESS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  GET_USER_FROM_TOKEN: 'GET_USER_FROM_TOKEN',
  LOG_OUT: 'LOG_OUT'
};

export default actionTypes;
